/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as IndiqueRouteImport } from './routes/indique'
import { Route as LivesRouteImport } from './routes/lives'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as QuentesRouteImport } from './routes/quentes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiAccountEnsureRouteImport } from './routes/api/account/ensure'
import { Route as ApiAccountSyncTokenRouteImport } from './routes/api/account/sync-token'
import { Route as ApiAdminCourtesyRouteImport } from './routes/api/admin/courtesy'
import { Route as ApiCheckoutStartRouteImport } from './routes/api/checkout/start'
import { Route as ApiScriptGenerateRouteImport } from './routes/api/script/generate'
import { Route as ApiTtsPreviewRouteImport } from './routes/api/tts/preview'
import { Route as ApiPublicChatReplyRouteImport } from './routes/api/public/chat/reply'
import { Route as ApiPublicGeminiGenerateRouteImport } from './routes/api/public/gemini/generate'
import { Route as ApiPublicGeminiTranscribeRouteImport } from './routes/api/public/gemini/transcribe'
import { Route as ApiPublicLiveConfigRouteImport } from './routes/api/public/live/config'
import { Route as ApiPublicLiveMappingRouteImport } from './routes/api/public/live/mapping'
import { Route as ApiPublicLiveSessionRouteImport } from './routes/api/public/live/session'
import { Route as ApiPublicLiveVerifyRouteImport } from './routes/api/public/live/verify'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicTtsSpeakRouteImport } from './routes/api/public/tts/speak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueRoute = IndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => rootRouteImport,
} as any)
const LivesRoute = LivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuentesRoute = QuentesRouteImport.update({
  id: '/quentes',
  path: '/quentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountEnsureRoute = ApiAccountEnsureRouteImport.update({
  id: '/api/account/ensure',
  path: '/api/account/ensure',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountSyncTokenRoute = ApiAccountSyncTokenRouteImport.update({
  id: '/api/account/sync-token',
  path: '/api/account/sync-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCourtesyRoute = ApiAdminCourtesyRouteImport.update({
  id: '/api/admin/courtesy',
  path: '/api/admin/courtesy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutStartRoute = ApiCheckoutStartRouteImport.update({
  id: '/api/checkout/start',
  path: '/api/checkout/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScriptGenerateRoute = ApiScriptGenerateRouteImport.update({
  id: '/api/script/generate',
  path: '/api/script/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsPreviewRoute = ApiTtsPreviewRouteImport.update({
  id: '/api/tts/preview',
  path: '/api/tts/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatReplyRoute = ApiPublicChatReplyRouteImport.update({
  id: '/api/public/chat/reply',
  path: '/api/public/chat/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeminiGenerateRoute = ApiPublicGeminiGenerateRouteImport.update({
  id: '/api/public/gemini/generate',
  path: '/api/public/gemini/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeminiTranscribeRoute =
  ApiPublicGeminiTranscribeRouteImport.update({
    id: '/api/public/gemini/transcribe',
    path: '/api/public/gemini/transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLiveConfigRoute = ApiPublicLiveConfigRouteImport.update({
  id: '/api/public/live/config',
  path: '/api/public/live/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveMappingRoute = ApiPublicLiveMappingRouteImport.update({
  id: '/api/public/live/mapping',
  path: '/api/public/live/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveSessionRoute = ApiPublicLiveSessionRouteImport.update({
  id: '/api/public/live/session',
  path: '/api/public/live/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveVerifyRoute = ApiPublicLiveVerifyRouteImport.update({
  id: '/api/public/live/verify',
  path: '/api/public/live/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTtsSpeakRoute = ApiPublicTtsSpeakRouteImport.update({
  id: '/api/public/tts/speak',
  path: '/api/public/tts/speak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/comprar': typeof ComprarRoute
  '/download': typeof DownloadRoute
  '/entrar': typeof EntrarRoute
  '/indique': typeof IndiqueRoute
  '/lives': typeof LivesRoute
  '/planos': typeof PlanosRoute
  '/quentes': typeof QuentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/account/ensure': typeof ApiAccountEnsureRoute
  '/api/account/sync-token': typeof ApiAccountSyncTokenRoute
  '/api/admin/courtesy': typeof ApiAdminCourtesyRoute
  '/api/checkout/start': typeof ApiCheckoutStartRoute
  '/api/script/generate': typeof ApiScriptGenerateRoute
  '/api/tts/preview': typeof ApiTtsPreviewRoute
  '/api/public/chat/reply': typeof ApiPublicChatReplyRoute
  '/api/public/gemini/generate': typeof ApiPublicGeminiGenerateRoute
  '/api/public/gemini/transcribe': typeof ApiPublicGeminiTranscribeRoute
  '/api/public/live/config': typeof ApiPublicLiveConfigRoute
  '/api/public/live/mapping': typeof ApiPublicLiveMappingRoute
  '/api/public/live/session': typeof ApiPublicLiveSessionRoute
  '/api/public/live/verify': typeof ApiPublicLiveVerifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tts/speak': typeof ApiPublicTtsSpeakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/comprar': typeof ComprarRoute
  '/download': typeof DownloadRoute
  '/entrar': typeof EntrarRoute
  '/indique': typeof IndiqueRoute
  '/lives': typeof LivesRoute
  '/planos': typeof PlanosRoute
  '/quentes': typeof QuentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/account/ensure': typeof ApiAccountEnsureRoute
  '/api/account/sync-token': typeof ApiAccountSyncTokenRoute
  '/api/admin/courtesy': typeof ApiAdminCourtesyRoute
  '/api/checkout/start': typeof ApiCheckoutStartRoute
  '/api/script/generate': typeof ApiScriptGenerateRoute
  '/api/tts/preview': typeof ApiTtsPreviewRoute
  '/api/public/chat/reply': typeof ApiPublicChatReplyRoute
  '/api/public/gemini/generate': typeof ApiPublicGeminiGenerateRoute
  '/api/public/gemini/transcribe': typeof ApiPublicGeminiTranscribeRoute
  '/api/public/live/config': typeof ApiPublicLiveConfigRoute
  '/api/public/live/mapping': typeof ApiPublicLiveMappingRoute
  '/api/public/live/session': typeof ApiPublicLiveSessionRoute
  '/api/public/live/verify': typeof ApiPublicLiveVerifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tts/speak': typeof ApiPublicTtsSpeakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/comprar': typeof ComprarRoute
  '/download': typeof DownloadRoute
  '/entrar': typeof EntrarRoute
  '/indique': typeof IndiqueRoute
  '/lives': typeof LivesRoute
  '/planos': typeof PlanosRoute
  '/quentes': typeof QuentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/api/account/ensure': typeof ApiAccountEnsureRoute
  '/api/account/sync-token': typeof ApiAccountSyncTokenRoute
  '/api/admin/courtesy': typeof ApiAdminCourtesyRoute
  '/api/checkout/start': typeof ApiCheckoutStartRoute
  '/api/script/generate': typeof ApiScriptGenerateRoute
  '/api/tts/preview': typeof ApiTtsPreviewRoute
  '/api/public/chat/reply': typeof ApiPublicChatReplyRoute
  '/api/public/gemini/generate': typeof ApiPublicGeminiGenerateRoute
  '/api/public/gemini/transcribe': typeof ApiPublicGeminiTranscribeRoute
  '/api/public/live/config': typeof ApiPublicLiveConfigRoute
  '/api/public/live/mapping': typeof ApiPublicLiveMappingRoute
  '/api/public/live/session': typeof ApiPublicLiveSessionRoute
  '/api/public/live/verify': typeof ApiPublicLiveVerifyRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/tts/speak': typeof ApiPublicTtsSpeakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/comprar'
    | '/download'
    | '/entrar'
    | '/indique'
    | '/lives'
    | '/planos'
    | '/quentes'
    | '/reset-password'
    | '/termos'
    | '/checkout/return'
    | '/api/account/ensure'
    | '/api/account/sync-token'
    | '/api/admin/courtesy'
    | '/api/checkout/start'
    | '/api/script/generate'
    | '/api/tts/preview'
    | '/api/public/chat/reply'
    | '/api/public/gemini/generate'
    | '/api/public/gemini/transcribe'
    | '/api/public/live/config'
    | '/api/public/live/mapping'
    | '/api/public/live/session'
    | '/api/public/live/verify'
    | '/api/public/payments/webhook'
    | '/api/public/tts/speak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/comprar'
    | '/download'
    | '/entrar'
    | '/indique'
    | '/lives'
    | '/planos'
    | '/quentes'
    | '/reset-password'
    | '/termos'
    | '/checkout/return'
    | '/api/account/ensure'
    | '/api/account/sync-token'
    | '/api/admin/courtesy'
    | '/api/checkout/start'
    | '/api/script/generate'
    | '/api/tts/preview'
    | '/api/public/chat/reply'
    | '/api/public/gemini/generate'
    | '/api/public/gemini/transcribe'
    | '/api/public/live/config'
    | '/api/public/live/mapping'
    | '/api/public/live/session'
    | '/api/public/live/verify'
    | '/api/public/payments/webhook'
    | '/api/public/tts/speak'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/comprar'
    | '/download'
    | '/entrar'
    | '/indique'
    | '/lives'
    | '/planos'
    | '/quentes'
    | '/reset-password'
    | '/termos'
    | '/checkout/return'
    | '/api/account/ensure'
    | '/api/account/sync-token'
    | '/api/admin/courtesy'
    | '/api/checkout/start'
    | '/api/script/generate'
    | '/api/tts/preview'
    | '/api/public/chat/reply'
    | '/api/public/gemini/generate'
    | '/api/public/gemini/transcribe'
    | '/api/public/live/config'
    | '/api/public/live/mapping'
    | '/api/public/live/session'
    | '/api/public/live/verify'
    | '/api/public/payments/webhook'
    | '/api/public/tts/speak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  ComprarRoute: typeof ComprarRoute
  DownloadRoute: typeof DownloadRoute
  EntrarRoute: typeof EntrarRoute
  IndiqueRoute: typeof IndiqueRoute
  LivesRoute: typeof LivesRoute
  PlanosRoute: typeof PlanosRoute
  QuentesRoute: typeof QuentesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiAccountEnsureRoute: typeof ApiAccountEnsureRoute
  ApiAccountSyncTokenRoute: typeof ApiAccountSyncTokenRoute
  ApiAdminCourtesyRoute: typeof ApiAdminCourtesyRoute
  ApiCheckoutStartRoute: typeof ApiCheckoutStartRoute
  ApiScriptGenerateRoute: typeof ApiScriptGenerateRoute
  ApiTtsPreviewRoute: typeof ApiTtsPreviewRoute
  ApiPublicChatReplyRoute: typeof ApiPublicChatReplyRoute
  ApiPublicGeminiGenerateRoute: typeof ApiPublicGeminiGenerateRoute
  ApiPublicGeminiTranscribeRoute: typeof ApiPublicGeminiTranscribeRoute
  ApiPublicLiveConfigRoute: typeof ApiPublicLiveConfigRoute
  ApiPublicLiveMappingRoute: typeof ApiPublicLiveMappingRoute
  ApiPublicLiveSessionRoute: typeof ApiPublicLiveSessionRoute
  ApiPublicLiveVerifyRoute: typeof ApiPublicLiveVerifyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTtsSpeakRoute: typeof ApiPublicTtsSpeakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique': {
      id: '/indique'
      path: '/indique'
      fullPath: '/indique'
      preLoaderRoute: typeof IndiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lives': {
      id: '/lives'
      path: '/lives'
      fullPath: '/lives'
      preLoaderRoute: typeof LivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quentes': {
      id: '/quentes'
      path: '/quentes'
      fullPath: '/quentes'
      preLoaderRoute: typeof QuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/ensure': {
      id: '/api/account/ensure'
      path: '/api/account/ensure'
      fullPath: '/api/account/ensure'
      preLoaderRoute: typeof ApiAccountEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/sync-token': {
      id: '/api/account/sync-token'
      path: '/api/account/sync-token'
      fullPath: '/api/account/sync-token'
      preLoaderRoute: typeof ApiAccountSyncTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/courtesy': {
      id: '/api/admin/courtesy'
      path: '/api/admin/courtesy'
      fullPath: '/api/admin/courtesy'
      preLoaderRoute: typeof ApiAdminCourtesyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/start': {
      id: '/api/checkout/start'
      path: '/api/checkout/start'
      fullPath: '/api/checkout/start'
      preLoaderRoute: typeof ApiCheckoutStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/script/generate': {
      id: '/api/script/generate'
      path: '/api/script/generate'
      fullPath: '/api/script/generate'
      preLoaderRoute: typeof ApiScriptGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/preview': {
      id: '/api/tts/preview'
      path: '/api/tts/preview'
      fullPath: '/api/tts/preview'
      preLoaderRoute: typeof ApiTtsPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat/reply': {
      id: '/api/public/chat/reply'
      path: '/api/public/chat/reply'
      fullPath: '/api/public/chat/reply'
      preLoaderRoute: typeof ApiPublicChatReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gemini/generate': {
      id: '/api/public/gemini/generate'
      path: '/api/public/gemini/generate'
      fullPath: '/api/public/gemini/generate'
      preLoaderRoute: typeof ApiPublicGeminiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gemini/transcribe': {
      id: '/api/public/gemini/transcribe'
      path: '/api/public/gemini/transcribe'
      fullPath: '/api/public/gemini/transcribe'
      preLoaderRoute: typeof ApiPublicGeminiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/config': {
      id: '/api/public/live/config'
      path: '/api/public/live/config'
      fullPath: '/api/public/live/config'
      preLoaderRoute: typeof ApiPublicLiveConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/mapping': {
      id: '/api/public/live/mapping'
      path: '/api/public/live/mapping'
      fullPath: '/api/public/live/mapping'
      preLoaderRoute: typeof ApiPublicLiveMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/session': {
      id: '/api/public/live/session'
      path: '/api/public/live/session'
      fullPath: '/api/public/live/session'
      preLoaderRoute: typeof ApiPublicLiveSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/verify': {
      id: '/api/public/live/verify'
      path: '/api/public/live/verify'
      fullPath: '/api/public/live/verify'
      preLoaderRoute: typeof ApiPublicLiveVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts/speak': {
      id: '/api/public/tts/speak'
      path: '/api/public/tts/speak'
      fullPath: '/api/public/tts/speak'
      preLoaderRoute: typeof ApiPublicTtsSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  ComprarRoute: ComprarRoute,
  DownloadRoute: DownloadRoute,
  EntrarRoute: EntrarRoute,
  IndiqueRoute: IndiqueRoute,
  LivesRoute: LivesRoute,
  PlanosRoute: PlanosRoute,
  QuentesRoute: QuentesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiAccountEnsureRoute: ApiAccountEnsureRoute,
  ApiAccountSyncTokenRoute: ApiAccountSyncTokenRoute,
  ApiAdminCourtesyRoute: ApiAdminCourtesyRoute,
  ApiCheckoutStartRoute: ApiCheckoutStartRoute,
  ApiScriptGenerateRoute: ApiScriptGenerateRoute,
  ApiTtsPreviewRoute: ApiTtsPreviewRoute,
  ApiPublicChatReplyRoute: ApiPublicChatReplyRoute,
  ApiPublicGeminiGenerateRoute: ApiPublicGeminiGenerateRoute,
  ApiPublicGeminiTranscribeRoute: ApiPublicGeminiTranscribeRoute,
  ApiPublicLiveConfigRoute: ApiPublicLiveConfigRoute,
  ApiPublicLiveMappingRoute: ApiPublicLiveMappingRoute,
  ApiPublicLiveSessionRoute: ApiPublicLiveSessionRoute,
  ApiPublicLiveVerifyRoute: ApiPublicLiveVerifyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTtsSpeakRoute: ApiPublicTtsSpeakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
